"""initialize album genre and guesses table

Revision ID: 5b3efb1fc90d
Revises: 
Create Date: 2019-05-25 22:23:54.410428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3efb1fc90d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('genre_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('album',
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('artist', sa.String(length=64), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.genre_id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['genre.genre_id'], ),
    sa.PrimaryKeyConstraint('album_id')
    )
    op.create_table('guess',
    sa.Column('guess_id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['album.album_id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.genre_id'], ),
    sa.PrimaryKeyConstraint('guess_id')
    )
    op.create_index(op.f('ix_guess_timestamp'), 'guess', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guess_timestamp'), table_name='guess')
    op.drop_table('guess')
    op.drop_table('album')
    op.drop_table('genre')
    # ### end Alembic commands ###
