"""add model_performance to genre

Revision ID: 64200a274e91
Revises: 5b3efb1fc90d
Create Date: 2019-05-31 21:13:13.197782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64200a274e91'
down_revision = '5b3efb1fc90d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genre', sa.Column('model_performance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('genre', 'model_performance')
    # ### end Alembic commands ###
